import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

// The shipped artifact is one file, but the sources are split by
// responsibility so they stay readable. Order matters and is declared here
// rather than inferred from the directory listing: tokens must land before
// anything that references them, and later layers deliberately override
// earlier ones (a shell restyles a primitive it contains). Alphabetical order
// would put `base` before `tokens` and quietly break the cascade.
export const ORDER = ['tokens.css', 'base.css', 'primitives.css']

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')

const BANNER = `/* axi design language - generated by scripts/build.mjs.
   Edit the files in src/ and run \`npm run build\`; do not edit this file. */
`

export function buildCss(order = ORDER) {
  const parts = order.map((name) => {
    const source = readFileSync(resolve(ROOT, 'src', name), 'utf8').trimEnd()
    return `/* --- ${name} --- */\n${source}`
  })
  return `${BANNER}\n${parts.join('\n\n')}\n`
}

// Only write when run directly, so importing this from a test never has the
// side effect of rewriting the artifact the test is about to check.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  mkdirSync(resolve(ROOT, 'dist'), { recursive: true })
  writeFileSync(resolve(ROOT, 'dist/axi.css'), buildCss())
  console.log(`built dist/axi.css from ${ORDER.length} source(s)`)
}
