import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

// The shipped artifact is one file, but the sources are split by
// responsibility so they stay readable. Order matters and is declared here
// rather than inferred from the directory listing: tokens must land before
// anything that references them, and later layers deliberately override
// earlier ones (a shell restyles a primitive it contains). Alphabetical order
// would put `base` before `tokens` and quietly break the cascade.
export const ORDER = ['tokens.css', 'base.css', 'primitives.css', 'layout.css', 'shells.css', 'data.css', 'prose.css']

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')

const BANNER = `/* axi design language - generated by scripts/build.mjs.
   Edit the files in src/ and run \`npm run build\`; do not edit this file. */
`

export function buildCss(order = ORDER) {
  const parts = order.map((name) => {
    const source = readFileSync(resolve(ROOT, 'src', name), 'utf8').trimEnd()
    return `/* --- ${name} --- */\n${source}`
  })
  return `${BANNER}\n${parts.join('\n\n')}\n`
}

// The accents are data, not stylesheet source: accents.json is the single
// source of truth and this generation is the only way dist/accents.css comes
// to exist. It cannot live as src/accents.css - ORDER must match src/ exactly
// and colour literals are forbidden outside tokens.css; accents are the
// second sanctioned home for colour literals precisely because they are
// generated from the data file. Opt-in: never concatenated into axi.css.
export const ACCENTS = JSON.parse(readFileSync(resolve(ROOT, 'accents.json'), 'utf8'))

export function buildAccentsCss(accents = ACCENTS) {
  const rules = accents
    .map((a) => `[data-axi-accent="${a.id}"] { --axi-accent: ${a.hex}; }`)
    .join('\n')
  return `${BANNER}\n${rules}\n`
}

// The knob table is generated into README.md between markers. It is the one
// table in this repo describing src/ that a human used to maintain by hand,
// and the one that could therefore go stale with no symptom at all - nothing
// imports a README.
import { KNOBS } from '../docs/manifest/knobs.mjs'

export function buildKnobTable(knobs = KNOBS) {
  const rows = knobs.map((k) => `| \`${k.name}\` | ${k.sets} | ${k.fallback} | \`${k.example}\` |`)
  return ['| Knob | Sets | Fallback | Example |', '|---|---|---|---|', ...rows].join('\n')
}

export function writeKnobTable(readme) {
  return readme.replace(
    /(<!-- axi:knobs -->\n)[\s\S]*?(\n<!-- \/axi:knobs -->)/,
    (_, open, close) => `${open}${buildKnobTable()}${close}`,
  )
}

// Only write when run directly, so importing this from a test never has the
// side effect of rewriting the artifact the test is about to check.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  mkdirSync(resolve(ROOT, 'dist'), { recursive: true })
  writeFileSync(resolve(ROOT, 'dist/axi.css'), buildCss())
  console.log(`built dist/axi.css from ${ORDER.length} source(s)`)
  writeFileSync(resolve(ROOT, 'dist/accents.css'), buildAccentsCss())
  console.log(`built dist/accents.css from ${ACCENTS.length} accent(s)`)

  const readmePath = resolve(ROOT, 'README.md')
  writeFileSync(readmePath, writeKnobTable(readFileSync(readmePath, 'utf8')))
  console.log(`wrote the knob table into README.md (${KNOBS.length} knobs)`)
}
